---
title: "Untitled"
format: html
---

# Introduction
```{r}
require(tidyverse)
require(terra)
require(tidyterra)
require(ggspatial)
require(magrittr)
require(sf)
require(leaflet)
require(leaflet.extras)
require(htmlwidgets)
```


# Method
## Layers

```{r}
mab = st_read('Data/spatial/tanga_pemba_biosphere_extent.gpkg')
mab  = mab  |> 
    mutate(area_m = st_area(geometry),
           area_km = as.numeric(area_m) / 1e6,
           area_ha = area_km * 100        
) 


cfmas = st_read('Data/spatial/cfmas_mainland_pemba.gpkg') |> 
    # st_make_valid() |> 
    st_sf()|> 
    st_transform(32737) |> 
    mutate(area_m = st_area(geom),
           area_km = as.numeric(area_m) / 1e6,
           area_ha = area_km * 100        
    ) |> 
    st_transform(4326)



islands = st_read('Data/spatial/islands.gpkg') |> 
    st_make_valid()

aoi = st_read('Data/spatial/tanga_pemba_biosphere_extent.gpkg')|> 
    st_make_valid()

aoi = aoi |> 
    st_transform(32737) |> 
    mutate(area_m = st_area(geometry),
           area_km = as.numeric(area_m) / 1e6,
           area_ha = area_km * 100        
    ) |> 
    st_transform(4326)


islands_aoi = islands |> 
    st_intersection(aoi)

mma = st_read('Data/spatial/mma.gpkg') |> janitor::clean_names()

shehia = st_read('Data/spatial/pemba/Shehia_Alomg_the_TAPE_hp.shp') |> 
    janitor::clean_names() |> 
    st_transform(4326) |> 
    select(name = ward_name)

coral = st_read('Data/spatial/coral_reefs_line.gpkg')
coral = coral |> 
    st_make_valid() |> 
    st_intersection(aoi)

mangroves_mainland = st_read('Data/spatial/mangrove_mainland.gpkg') |> mutate(area="Mainland") |> select(area)
mangroves_pemba = st_read('Data/spatial/mangrove_pemba.gpkg') |> mutate(area="Pemba") |> select(area)

mangroves = rbind(mangroves_mainland, mangroves_pemba)

mangroves = mangroves |> 
    st_make_valid() |> 
    st_intersection(aoi)


depth_contour = st_read('Data/spatial/depth_contour.gpkg')

depth_iso200 = depth_contour |> 
    filter(depth == -100)


miamba_fungu = st_read('Data/spatial/island_miamba_fungu.gpkg') |> 
    st_make_valid() |> 
    janitor::clean_names()

miamba_fungu = miamba_fungu |> filter(!type == 'Submerged')|> 
    mutate(area_m = st_area(geom),
           area_km = as.numeric(area_m) / 1e6,
           area_ha = area_km * 100        
    ) |> 
    st_transform(4326)

fungu_core = miamba_fungu |> 
    filter(zone == 'Core') |> 
    select(name)

# zone_fungu = fungu_core |> 
#     st_transform(32737) |> 
#     st_buffer(dist = c(2000)) |> 
#     st_union() |> 
#     st_sf() |> 
#     st_transform(4326) 

```


```{r}
islands_aoi = islands_aoi |> 
    select(name = NAME) |> 
    rbind(fungu_core) |> 
    mutate(area_m = st_area(geom),
           area_km = as.numeric(area_m) / 1e6,
           area_ha = area_km * 100        
    ) |> 
    select(-area_m) |> 
    filter(!name == 'Pemba Island') 

zones = islands_aoi  |> 
    st_transform(32737) |> 
    st_buffer(dist = c(2000)) |> 
    st_union() |> 
    st_sf() |> 
    st_transform(4326)


```


```{r}

tape = leaflet() |> 
    setView(lng = 39.5, lat = -5.2, zoom = 10) |>
    addProviderTiles(providers$Esri.WorldImagery, group = "ESRI Imagery") |>
    addProviderTiles(providers$Esri.OceanBasemap, group = "Ocean Basemap") |>
    addProviderTiles(providers$OpenTopoMap, group = "Topographic") |>
    addTiles(group = "OpenStreetMap") |>
    addPolygons(data = shehia, group = 'Shehia',
                fill = TRUE, color = 'black',
                weight = 1, fillOpacity = .1, opacity = 1, label = ~name,
            )|>
    addPolygons(data = mangroves, group = 'Mikoko',
                fill = TRUE, color = 'transparent', fillColor = 'darkgreen',
                weight = 0, fillOpacity = .6, opacity = 1
            ) |>
    addPolygons(data = mab, group = 'Hifadhi Hai',
                fillColor = 'blue', color = 'black', 
                weight = 2,     
                fillOpacity = 0.1, opacity = 1, 
                label = ~htmltools::htmlEscape(name), 
                popup = ~paste0("<strong>Name: </strong>", name, 
                                # "<br><strong>Class: </strong>", class,
                                "<br><strong>Area (ha): </strong>", scales::comma(area_ha),
                                "<br><strong>Area (km): </strong>",  scales::comma(area_km)
                            ),
                labelOptions = labelOptions(noHide = F, direction = 'auto')
            ) |>
    addPolygons(data = mma, group = 'MPA/MCA',
                fillColor = 'blue', color = 'blue', 
                weight = 2,     
                fillOpacity = 0.5, opacity = 1, 
                label = ~htmltools::htmlEscape(name), 
                popup = ~paste0("<strong>Name: </strong>", name, 
                                "<br><strong>Class: </strong>", class,
                                "<br><strong>Area (ha): </strong>", round(mma_area_h, 2)),
                labelOptions = labelOptions(noHide = F, direction = 'auto')
            ) |>
    addPolygons(data = cfmas, group = 'Eneo Mpito',
                fillColor = 'red', color = 'red', # Fill and stroke color
                weight = 2,      # Stroke width
                fillOpacity = 0.2, opacity = 1, 
                label = ~htmltools::htmlEscape(name), 
                popup = ~paste0("<strong>Name: </strong>", name, 
                                # "<br><strong>Class: </strong>", class,
                                "<br><strong>Area (ha): </strong>", scales::comma(area_ha),
                                "<br><strong>Area (km): </strong>",  scales::comma(area_km)
                            ),
                labelOptions = labelOptions(noHide = F, direction = 'auto')
            ) |>
    addPolygons(data = islands_aoi, group = 'Eneo Msingi',
                fillColor = 'darkgreen', color = 'darkgreen',
                weight = 2, fillOpacity = 0.5, opacity = 1, 
                label = ~htmltools::htmlEscape(name), 
                popup = ~paste0("<strong>Name: </strong>", name, 
                                # "<br><strong>Class: </strong>", class,
                                "<br><strong>Area (ha): </strong>", round(area_ha, 2)),
                labelOptions = labelOptions(noHide = F, direction = 'auto')
            ) |>
    addPolygons(data = zones, group = 'Eneo Kinga',
                fillColor = 'yellow', color = 'orange',
                weight = 2, fillOpacity = 0.5, opacity = 1
            ) |>
    addPolygons(data = miamba_fungu, group = 'Other Islands',
                fillColor = 'purple', color = 'purple',
                weight = 2, fillOpacity = 0.5, opacity = 1
            )|>
    addPolylines(data = coral, group = 'Matumbawe', stroke = TRUE, weight = 2, color = 'orange', opacity = 1) |>
    addPolylines(data = depth_iso200, group = '200 meter', stroke = TRUE, weight = 2, color = 'black', opacity = 1) |>
    # addLayersControl(
    #     baseGroups = c("OpenStreetMap", "ESRI Imagery", "Ocean Basemap", "Topographic"),
    #     # overlayGroups = c('Eneo Msingi', 'Eneo Kinga', 'Eneo Mpito', 'Hifadhi Hai', 'MPA/MCA', 'Drawn Items', 'Graticule'),
    #     position = "bottomright",
    #     options = layersControlOptions(collapsed = FALSE)
    # ) |>
    addLayersControl(
        baseGroups = c("OpenStreetMap", "ESRI Imagery", "Ocean Basemap", "Topographic"),
        overlayGroups = c('Eneo Msingi', 'Eneo Kinga', 'Eneo Mpito', 'Hifadhi Hai','Shehia','Other Islands','Matumbawe', 'Mikoko', 'MPA/MCA','200 meter', 'Drawn Items', 'Graticule'),
        position = "topright",
        options = layersControlOptions(collapsed = FALSE)
    ) |>  
        hideGroup(group = c('Shehia','Other Islands', 'Hifadhi Hai','Matumbawe', 'Mikoko', 'MPA/MCA','200 meter', 'Drawn Items', 'Graticule'))|>
    # Legend for the filled polygons
    addLegend(
        position = "bottomright",
        colors = c("blue", "yellow", "red", "green"),
        labels = c("Eneo Kinga", "Eneo Mpito","Eneo Msingi",  "MPA/MCA"),
        title = "Legend",
        opacity = 1
    ) |>
    # Add a separate legend for the TAPE outline
    # addLegend(
    #     position = "bottomright",
    #     colors = "black",
    #     labels = "TAPE Biosphere Extent",
    #     opacity = 1
    # ) |>
    addMiniMap(
        # tiles = providers$Esri.OceanBasemap,
        toggleDisplay = TRUE, 
        position = 'bottomleft',
        minimized = FALSE
    ) |>
    addScaleBar(position = "bottomleft") |> 
    addFullscreenControl() |> 
    addDrawToolbar(
        targetGroup = 'Drawn Items',
        editOptions = editToolbarOptions(
            selectedPathOptions = selectedPathOptions()
        ),
        polylineOptions = FALSE, circleOptions = FALSE, rectangleOptions = TRUE, markerOptions = TRUE, circleMarkerOptions = FALSE
    ) |> 
    addMeasure(
        position = "topleft",
        primaryLengthUnit = "meters", secondaryLengthUnit = "kilometers",
        primaryAreaUnit = "sqmeters", secondaryAreaUnit = "hectares",
        activeColor = "#3D535D",
        completedColor = "#7D4479") |> 
    addGraticule(
        interval = 0.2,
        style = list(color = "#333", weight = 0.8, opacity = 0.5),
        group = "Graticule",
        options = pathOptions(pointerEvents = "none", clickable = FALSE)
    )  


tape
tape |> 
    htmlwidgets::saveWidget(file = 'index.html')


``` 


```{r}

```